### ISSUE TITLE
[1.19.2] Crash on loading World after Update

### ISSUE THREAD

**Issue by FryoKnight** [Rikurob/Vmh#2]
After updating from from v1.1.6 to v1.2.2, my world crashes any time I try to load into it.
I tried deleting the configs to see if that would fix it, but it did not.

Downgading is currently a fix the issue for now.

Here is a pastebin of the crash:
https://pastebin.com/euQsjaiJ

**Comment by Rikurob** [comment]
I had no issues loading it so, it has to do with the config, there were extensive config changes, and the way they are generated could cause issues with updating. There should be an option to regenerate configs if they don't exist that should fix the issue if you delete all the configs and set that to true for one run. This is due to the fact that some people might not want those configs to be available and I don't want the mod to recreate them if they are deleted.

**Comment by FryoKnight** [comment]
I deleted the configs, and regenerated them.
Game is still hard crashing when loading into my old world.
Started up new world and no issues.

And now I can load my old world after loading the new one?
I will see if this fixed it long term or not. Not really sure what or how it was fixed though...

**Comment by Rikurob** [comment]
It should be, that is weird though, but glad Its fixed lol.

**Comment by theshadowake** [comment]
I am having this same issue in the latest 1.18.2 version (exact same crash). Deleting the configs is only a temp fix as it seems to happen at any point randomly after the first launch with fresh configs.
